---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8000}]

provisioner:
  name: chef_solo
  require_chef_omnibus: latest
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[ubumirror]
  -name: webmirror
    run_list:
      - recipe[apt]
      - recipe[apache2]
      - recipe[ubumirror]
